CREATE TABLE [dbo].[Address] (
    [AddressId]                     INT            IDENTITY (1, 1) NOT NULL,
    [AddressLine1]                  NVARCHAR (255) NOT NULL,
    [AddressLine2]                  NVARCHAR (255) NOT NULL,
    [City]                          NVARCHAR (255) NOT NULL,
    [State]                         NVARCHAR (50)  NOT NULL,
    [ZipCode]                       NVARCHAR (12)  NOT NULL,
    [HomePhone]                     NVARCHAR (255) NOT NULL,
    [CellPhone]                     NVARCHAR (255) NOT NULL,
    [SpecialContactInfo]            NVARCHAR (255) NOT NULL,
    [SpecialForwardingInstructions] NVARCHAR (255) NOT NULL,
    [DepartComment]                 NVARCHAR (255) NOT NULL,
    [SpecialHandlingInstructions]   NVARCHAR (255) NOT NULL,
    [DateEntered]                   DATETIME       NULL,
    [AuditTrail]                    VARCHAR (2000) NOT NULL,
    [AddressLine3]                  NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [AddressLine4]                  NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [BoxNumber]                     NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [BuildingCode]                  NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [CubicleNumber]                 NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [DeliveryCode]                  NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [DirectPhone]                   NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [DirectoryAddress]              NVARCHAR (MAX) DEFAULT (N'') NOT NULL,
    [DirectoryBuilding]             NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [DirectoryCity]                 NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [DirectoryHomePhone]            NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [DirectoryInclude]              BIT            NULL,
    [DirectoryName]                 NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [DirectoryOfficePhone]          NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [DirectoryRoom]                 NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [DirectoryWorkgroup]            NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [DirectoryZip]                  NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [IncludeInDirectory]            BIT            DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [IsActive]                      BIT            DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [MailListFlag]                  BIT            NULL,
    [MailOnly]                      BIT            NULL,
    [MailSortName]                  NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [OfficeFAX]                     NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [OfficePhone]                   NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [RoomNumber]                    NVARCHAR (255) DEFAULT (N'') NOT NULL,
    CONSTRAINT [PK_Addresses] PRIMARY KEY CLUSTERED ([AddressId] ASC)
);

